{% set name = "perl-module-pluggable" %}
{% set version = "6.1" %}
{% set sha256 = "4239d4c8222a17f0fead043d810339d6c18a080b5e79c23567fcb159ad8730ff" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SI/SIMONW/Module-Pluggable-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-base
    - perl-data-dumper
    - perl-exporter
    - perl-file-path
    - perl-file-temp
    - perl-pathtools
    - perl-test-simple
  run:
    - perl
    - perl-exporter

test:
  imports:
    - Module::Pluggable
    - Module::Pluggable::Object

about:
  home: https://metacpan.org/dist/Module-Pluggable
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: 'automatically give your module the ability to have plugins'
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
